version: '3'
services:
  pod:
    build:
      context: .
      args:
        - PORT=3060
        - APP_ENV=.env-local
    ports:
      - "3060:3060"
    command: npm start
    volumes:
      - ./:/app
      - /app/node_modules
